MODULE [foreign] Math; IMPORT SYSTEM;

CONST
  Pi* = 3.1415926535; E* = 2.7182818285;

PROCEDURE- Sin* (x: SYSTEM.REAL64): REAL;
PROCEDURE- Cos* (x: SYSTEM.REAL64): REAL;
PROCEDURE- ArcTan* (x: SYSTEM.REAL64): REAL;
PROCEDURE- Exp* (x: SYSTEM.REAL64): REAL;
PROCEDURE- Sqrt* (x: SYSTEM.REAL64): REAL;
PROCEDURE- Ln* (x: SYSTEM.REAL64): REAL;
PROCEDURE- Pow* (x, y: SYSTEM.REAL64): REAL;
PROCEDURE- Randomize*;
PROCEDURE- RndRange* (min, max: INT16): INT16;

END Math.
