MODULE [foreign] Strings; IMPORT SYSTEM;

PROCEDURE Length* (s: ARRAY OF CHAR): INT16;
PROCEDURE IntToStr* (n: INT16; VAR str: ARRAY OF CHAR): BOOLEAN;
PROCEDURE UIntToStr* (n: INT16; VAR str: ARRAY OF CHAR): BOOLEAN;
PROCEDURE StrToInt* (str: ARRAY OF CHAR; VAR result: INT16): BOOLEAN;

END Strings.
